spring:
  application:
    name: monkeybusiness-server
  
  datasource:
    url: jdbc:postgresql://10.23.137.54:5432/monkey_business
    username: postgres
    password: n3u3d4!
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        '[dialect]': org.hibernate.dialect.PostgreSQLDialect
        '[format_sql]': true
        '[use_sql_comments]': true
    show-sql: false
    open-in-view: false
  
server:
  port: 8080
  servlet:
    context-path: /api
