---
config:
    theme: dark
---
classDiagram
    %% Animal <|-- Duck
    %% Animal <|-- Fish
    %% Animal <|-- Zebra
    %% Animal : +int age
    %% Animal : +String gender
    %% Animal: +isMammal()
    %% Animal: +mate()
    User <|-- Duck
    User <|-- Fish
    User <|-- Zebra
    User : -UUID final userID
    User : -String final email
    User : -String final password
    User : -ENUM accessLevel
    User : -bool isAuthenticated
    User : -Set<Account> accounts
    User : -ZonedDateTime lastLogin
    User : +login()
    User : +logout()
    User : +getAccount()
    User : +checkStatus()
    User : +checkAccessLevel()
    User : +changePassword()
    class Duck{
      +String beakColor
      +swim()
      +quack()
    }
    class Fish{
      -int sizeInFeet
      -canEat()
    }
    class Zebra{
      +bool is_wild
      +run()
    }